spring:
    application:
        name: app
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306
        username: starter
        password: starter
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
        default-schema: starter
        enabled: true
        drop-first: false

server:
    port: 8080

custom:
    name: ${spring.application.name}
    mock:
        url: http://localhost:8080
        username: mock
        password: mock

